#!/usr/bin/env node

import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';

const DEFAULT_SUMMARY_PATH = 'tests/compat/stylelint/baseline/compat-summary.json';
const DEFAULT_OUTPUT_PATH = 'crates/csslint-rules/src/vendor_prefix_allowlist.rs';
const STYLELINT_ALLOWLIST_PATH = 'lib/utils/isAutoprefixable.mjs';

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const commit = args.commit ?? (await readPinnedStylelintCommit(args.summaryPath));
  const sourceUrl = `https://raw.githubusercontent.com/stylelint/stylelint/${commit}/${STYLELINT_ALLOWLIST_PATH}`;
  const sourceText = await fetchText(sourceUrl);

  const properties = parseSetValues(sourceText, 'PROPERTIES');
  const propertyValues = parseSetValues(sourceText, 'PROPERTY_VALUES');

  if (properties.length === 0) {
    throw new Error('parsed zero PROPERTIES values from Stylelint source');
  }
  if (propertyValues.length === 0) {
    throw new Error('parsed zero PROPERTY_VALUES values from Stylelint source');
  }

  const rendered = renderRustModule({
    sourceUrl,
    properties,
    propertyValues,
  });

  await fs.mkdir(path.dirname(args.outputPath), { recursive: true });
  await fs.writeFile(args.outputPath, rendered, 'utf8');

  process.stdout.write(
    `Wrote ${properties.length} properties and ${propertyValues.length} values to ${args.outputPath}\n`
  );
}

function parseArgs(argv) {
  const parsed = {
    commit: null,
    summaryPath: DEFAULT_SUMMARY_PATH,
    outputPath: DEFAULT_OUTPUT_PATH,
  };

  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === '--commit') {
      parsed.commit = argv[++i] ?? null;
    } else if (arg === '--summary-path') {
      parsed.summaryPath = argv[++i] ?? DEFAULT_SUMMARY_PATH;
    } else if (arg === '--output') {
      parsed.outputPath = argv[++i] ?? DEFAULT_OUTPUT_PATH;
    } else if (arg === '-h' || arg === '--help') {
      throw new Error(
        'usage: node scripts/extract_stylelint_vendor_allowlist.mjs [--commit <stylelint-commit>] [--summary-path tests/compat/stylelint/baseline/compat-summary.json] [--output crates/csslint-rules/src/vendor_prefix_allowlist.rs]'
      );
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }

  return parsed;
}

async function readPinnedStylelintCommit(summaryPath) {
  const raw = await fs.readFile(summaryPath, 'utf8');
  const parsed = JSON.parse(raw);
  const commit = parsed?.source?.commit;
  if (typeof commit !== 'string' || commit.trim().length === 0) {
    throw new Error(`could not read source.commit from ${summaryPath}`);
  }
  return commit.trim();
}

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to fetch ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function parseSetValues(sourceText, setName) {
  const marker = `const ${setName} = new Set([`;
  const start = sourceText.indexOf(marker);
  if (start === -1) {
    throw new Error(`could not locate '${marker}' in stylelint source`);
  }

  const bodyStart = start + marker.length;
  const bodyEnd = sourceText.indexOf(']);', bodyStart);
  if (bodyEnd === -1) {
    throw new Error(`could not locate closing ']);' for ${setName}`);
  }

  const body = sourceText.slice(bodyStart, bodyEnd);
  const entries = new Set();
  const regex = /'((?:\\.|[^'])*)'/g;

  for (const match of body.matchAll(regex)) {
    const encoded = match[1];
    entries.add(decodeSingleQuotedLiteral(encoded));
  }

  return [...entries].sort((left, right) => left.localeCompare(right));
}

function decodeSingleQuotedLiteral(value) {
  return value.replace(/\\'/g, "'").replace(/\\\\/g, '\\');
}

function renderRustModule({ sourceUrl, properties, propertyValues }) {
  return [
    '// This file is generated by scripts/extract_stylelint_vendor_allowlist.mjs.',
    `// Source: ${sourceUrl}`,
    '// Do not edit manually.',
    '',
    renderRustArray('AUTOPREFIXABLE_PROPERTIES', properties),
    '',
    renderRustArray('AUTOPREFIXABLE_PROPERTY_VALUES', propertyValues),
    '',
    'pub(super) fn is_autoprefixable_property(property: &str) -> bool {',
    '    AUTOPREFIXABLE_PROPERTIES.binary_search(&property).is_ok()',
    '}',
    '',
    'pub(super) fn is_autoprefixable_property_value(value: &str) -> bool {',
    '    AUTOPREFIXABLE_PROPERTY_VALUES.binary_search(&value).is_ok()',
    '}',
    '',
  ].join('\n');
}

function renderRustArray(name, values) {
  const lines = values.map((value) => `    ${JSON.stringify(value)},`);
  return [`pub(super) const ${name}: [&str; ${values.length}] = [`, ...lines, '];'].join('\n');
}

main().catch((error) => {
  process.stderr.write(`${error.message}\n`);
  process.exit(2);
});
